modLoader="javafml"
loaderVersion="[43,)"
license="Not specified"

[[mods]]
modId="madokraftmagica"
version="1.0.0"
displayName="MadokraftMagica"
displayURL="https://mcreator.net"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="MCreator"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.madokraftmagica]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2]"
    ordering="AFTER"
    side="BOTH"

[[dependencies.madokraftmagica]]
    modId="forge"
    mandatory=true
    versionRange="[43,)"
    ordering="NONE"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration